name: Java CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Install Allure via NPM
        run: |
          npm install -g allure-commandline --save-dev
          
      - name: Run Tests
        run: mvn clean test

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
