name: Java CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run Tests
        run: mvn test
        
      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report
          allure open -h 127.0.0.1 -p 5050
          
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: testReport/
